version: '3.8'
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/prisma/
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
